import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'

import { useEffect, useState } from 'react'
import supabase from '@/utils/supabaseClient'

export default function Home() {
  const [isAuthenicated, setIsAuthenicated] = useState<boolean>(false)
  const [userId, setUserId] = useState<string | undefined>()
  useEffect(() => {
    const getUser = async () => {
      const user = await supabase.auth.getUser()
      console.log("user", user)

      if (user) {
        const userId = user.data.user?.id
        setIsAuthenicated(true)
        setUserId(userId)
      }
    }

    getUser()
  }, [])

  return (
    <>
      <Head>
        <title>Linktree Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline">Hello</h1>
    </>
  )
}
